language: node_js

node_js:
  - '6'

services:
  - mongodb
  - rabbitmq

env:
  - RABBITMQ_URI=amqp://localhost MONGODB_URI=mongodb://localhost WEB_URI=http://localhost:3000 WEB_PORT=3000

install:
  - npm install -g yarn
  - cd lib/amqp && yarn install && cd ../../
  - cd web && yarn install && cd ../
  - cd worker && yarn install && cd ../
  - cd e2e && yarn install && cd ../

script:
  - npm run --prefix lib/amqp lint
  - npm run --prefix web lint
  - npm run --prefix worker lint
  - npm run --prefix e2e lint
  - npm run --prefix web test
  - npm run --prefix worker test
  - npm run --prefix lib/amqp test
  - npm start --prefix web
  - npm start --prefix worker
  - npm run --prefix e2e test

notifications:
  email: false
