language: node_js

node_js:
  - '6'

services:
  - mongodb
  - rabbitmq

env:
  - RABBITMQ_URI=amqp://localhost MONGODB_URI=mongodb://localhost

install:
  - npm install --prefix lib/amqp
  - npm install --prefix web
  - npm install --prefix worker
  - npm install --prefix e2e

script:
  - npm run --prefix lib/amqp lint
  - npm run --prefix web lint
  - npm run --prefix worker lint
  - npm run --prefix e2e lint
  - npm run --prefix lib/amqp test
  - npm run --prefix web test
  - npm run --prefix worker test

notifications:
  email: false
