language: node_js

node_js:
  - '6'

services:
  - mongodb
  - rabbitmq

env:
  - RABBITMQ_URI=amqp://localhost MONGODB_URI=mongodb://localhost

install:
  - npm install -g yarn
  - cd lib/amqp && yarn install
  - cd web && yarn install
  - cd worker && yarn install
  - cd e2e && yarn install

script:
  - npm run --prefix lib/amqp lint
  - npm run --prefix web lint
  - npm run --prefix worker lint
  - npm run --prefix e2e lint
  - npm run --prefix web test
  - npm run --prefix worker test
  - npm run --prefix lib/amqp test

notifications:
  email: false
