version: '3'
services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: none
  mongo:
    ports:
      - "27017:27017"
    logging:
      driver: none
  worker:
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSomeGoogleMapApiKeyThatIs39CharLong
  e2e:
    image: node:6
    volumes:
      - .:/app
    working_dir: /app/e2e
    depends_on:
      - web
      - worker
    command: npm run test
