version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
    volumes:
      - ./volumes/mongo:/data/db
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    environment:
      - WEB_PORT=80
    depends_on:
      - mongo
      - rabbitmq
    command: npm start
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=AIzaSomeGoogleMapApiKeyThatIs39CharLong
    depends_on:
      - rabbitmq
    command: npm start
